spring:
    application:
        name: sensitiveword
    datasource:
        url: jdbc:mysql://localhost:3306/jpa-test?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true
server:
  #???
  port: 8888
  tomcat:
        max-http-post-size: -1
